name: Sync Wiki on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: repo

    - name: Sync files to Wiki.git
      run: |
        # Replace 'path/to/wiki.git' with the actual path to your Wiki.git repository
        WIKI_PATH=https://github.com/lcxznpy/AWW.wiki.git
        # COMMIT_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        git clone https://github.com/lcxznpy/AWW.wiki.git
        ls -la
        pwd
        # for file in $COMMIT_FILES; do
        #   cp -f "$file" "AWW.wiki/$file"
        # done
        
        cd  ${{ github.workspace }}/AWW.wiki
        ls -la
        pwd
        rm -rf *.md
        cp ../repo/*md ./
        ls -la
        pwd
        git config --global user.email "github@robot.com"
        git config --global user.name "github robot"
        git add .
        git commit -m "Sync changes from main repository"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACTION }}
